import { Track } from "./sharedTypes/sharedTypes";

export const data: Track[] = [
    {
        _id: 1,
        name: 'TestName',
        author: 'TestAuthor1',
        release_date: '2005-06-11',
        genre: ['TestGenre4'],
        duration_in_seconds: 205,
        album: 'TestAlbum',
        logo: null,
        track_file: 'TestTrack_file.mp3',
        stared_user: [],
    },
    {
        _id: 2,
        name: 'TestName',
        author: 'TestAuthor2',
        release_date: '2012-06-11',
        genre: ['TestGenre3'],
        duration_in_seconds: 412,
        album: 'TestAlbum',
        logo: null,
        track_file: 'TestTrack_file.mp3',
        stared_user: [],
    },
    {
        _id: 3,
        name: 'TestName',
        author: 'TestAuthor3',
        release_date: '2005-09-11',
        genre: ['TestGenre1'],
        duration_in_seconds: 600,
        album: 'TestAlbum',
        logo: null,
        track_file: 'TestTrack_file.mp3',
        stared_user: [],
    },
    {
        _id: 4,
        name: 'TestName',
        author: 'TestAuthor4',
        release_date: '2005-06-18',
        genre: ['TestGenre5'],
        duration_in_seconds: 500,
        album: 'TestAlbum',
        logo: null,
        track_file: 'TestTrack_file.mp3',
        stared_user: [],
    },
    {
        _id: 5,
        name: 'TestName',
        author: 'TestAuthor5',
        release_date: '2012-12-12',
        genre: ['TestGenre'],
        duration_in_seconds: 400,
        album: 'TestAlbum',
        logo: null,
        track_file: 'TestTrack_file.mp3',
        stared_user: [],
    },
    {
        _id: 6,
        name: 'TestName',
        author: 'TestAuthor5',
        release_date: '2012-12-12',
        genre: ['TestGenre'],
        duration_in_seconds: 400,
        album: 'TestAlbum',
        logo: null,
        track_file: 'TestTrack_file.mp3',
        stared_user: [],
    },
]